# Generated by Django 4.2.1 on 2024-04-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('Hotspot_ID', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('Hotspot_Name', models.CharField(max_length=50)),
                ('Hotspot_Latitude', models.CharField(max_length=50)),
                ('Hotspot_longitude', models.CharField(max_length=50)),
                ('Food_needed', models.IntegerField()),
                ('Satisfied', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('Restaurant_ID', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('Restaurant_Name', models.CharField(max_length=50)),
                ('Restaurant_Latitude', models.CharField(max_length=50)),
                ('Restaurant_longitude', models.CharField(max_length=50)),
                ('Restaurant_Rating', models.IntegerField()),
                ('Food_available', models.IntegerField()),
            ],
        ),
    ]
