# Generated by Django 4.2.1 on 2024-04-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspot',
            name='Hotspot_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='Restaurant_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
