# Generated by Django 4.2.1 on 2024-04-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0002_alter_hotspot_hotspot_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_details', models.TextField()),
                ('user_identifier', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
    ]
