# Generated by Django 4.2.1 on 2024-04-30 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0003_foodrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodRequest',
        ),
    ]
