# Generated by Django 4.2.1 on 2024-04-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0004_delete_foodrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Restaurant_ID', models.IntegerField()),
                ('Supplier_name', models.CharField(max_length=50)),
                ('food_details', models.TextField()),
                ('user_identifier', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
    ]
